version: '3.9'
services:
  track-service:
    image: track_image
    container_name: track-service
    build:  userTrackService/
    restart: always
    network_mode: user-network
    ports:
      - 64100:64100
    depends_on:
      - mongoService

  mongoService:
    image: mongo
    container_name: mongoService
    ports:
      - 27017:27017
    network_mode: user-network

  authentication-service:
    image: authentication_image
    container_name: authentication-service
    build: userAuthentication/
    restart: always
    network_mode: user-network
    ports:
      - 64200:64200
    depends_on:
      - mysqlService

  mysqlService:
    image: mysql:latest
    container_name: mysqlService
    network_mode: user-network
    ports:
      - 3306:3306

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"